"""
Revision ID: 420508eb3eb3
Revises: 
Create Date: 2025-11-04 13:21:34.446533
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '420508eb3eb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorygroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=1), nullable=False),
    sa.Column('code_gg', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'code_gg', name='uq_group_code')
    )
    op.create_table('creditcardstatement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CLOSED', 'PAID', name='creditcardstatementstatus'), nullable=False),
    sa.Column('settlement_transaction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['settlement_transaction_id'], ['transaction.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('exchangerate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base', sa.String(length=3), nullable=False),
    sa.Column('quote', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base', 'quote', 'date', name='uq_fx_snapshot')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('occurred_time', sa.Time(), nullable=True),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', 'SETTLEMENT', name='txn_type'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('from_account_id', sa.Integer(), nullable=True),
    sa.Column('to_account_id', sa.Integer(), nullable=True),
    sa.Column('card_account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('imported_source_id', sa.String(length=128), nullable=True),
    sa.Column('is_card_charge', sa.Boolean(), nullable=False),
    sa.Column('is_balance_neutral', sa.Boolean(), nullable=False),
    sa.Column('is_auto_transfer_match', sa.Boolean(), nullable=False),
    sa.Column('exclude_from_reports', sa.Boolean(), nullable=False),
    sa.Column('linked_transaction_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('CLEARED', 'PENDING_PAYMENT', name='txn_status'), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(type != 'SETTLEMENT') OR card_account_id IS NOT NULL", name='ck_txn_settlement_requires_card'),
    sa.CheckConstraint("(type = 'TRANSFER' AND from_account_id IS NOT NULL AND to_account_id IS NOT NULL AND from_account_id != to_account_id) OR (type = 'EXPENSE' AND from_account_id IS NOT NULL) OR (type = 'INCOME' AND to_account_id IS NOT NULL) OR (type = 'SETTLEMENT' AND from_account_id IS NOT NULL AND to_account_id IS NOT NULL)", name='ck_txn_account_rules'),
    sa.CheckConstraint('(is_card_charge = 0) OR (card_account_id IS NOT NULL)', name='ck_txn_card_charge_requires_card'),
    sa.CheckConstraint('from_account_id IS NOT NULL OR to_account_id IS NOT NULL', name='ck_txn_requires_account'),
    sa.CheckConstraint('linked_transaction_id IS NULL OR linked_transaction_id != id', name='ck_txn_not_link_self'),
    sa.ForeignKeyConstraint(['card_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['from_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['transfergroup.id'], ),
    sa.ForeignKeyConstraint(['linked_transaction_id'], ['transaction.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payee_id'], ['payee.id'], ),
    sa.ForeignKeyConstraint(['statement_id'], ['creditcardstatement.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['to_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('linked_transaction_id', name='uq_txn_linked_transaction_id'),
    sa.UniqueConstraint('user_id', 'external_id', name='uq_txn_external_id'),
    sa.UniqueConstraint('user_id', 'imported_source_id', name='uq_txn_imported_source_id')
    )
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index('ix_txn_card_account_id', ['card_account_id'], unique=False)
        batch_op.create_index('ix_txn_user_date', ['user_id', 'occurred_at'], unique=False)

    op.create_table('transfergroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'SAVINGS', 'LOAN', 'CREDIT_LINE', 'RETIREMENT', 'FUND', 'STOCK', 'CRYPTO', 'OTHER', 'CHECK_CARD', 'CREDIT_CARD', name='account_type'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('institution', sa.String(length=120), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('linked_account_id', sa.Integer(), nullable=True),
    sa.Column('opened_at', sa.Date(), nullable=True),
    sa.Column('closed_at', sa.Date(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("type != 'CREDIT_CARD' OR linked_account_id IS NOT NULL", name='ck_credit_card_requires_link'),
    sa.CheckConstraint('linked_account_id IS NULL OR linked_account_id != id', name='ck_account_link_not_self'),
    sa.ForeignKeyConstraint(['linked_account_id'], ['account.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_account_name')
    )
    op.create_table('calendarevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('ANNIVERSARY', 'MEMO', 'REMINDER', name='calendareventtype'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendarevent', schema=None) as batch_op:
        batch_op.create_index('ix_calendar_event_user_date', ['user_id', 'date'], unique=False)

    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('code_cc', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('full_code', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['categorygroup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_code', name='uq_category_full_code'),
    sa.UniqueConstraint('group_id', 'code_cc', name='uq_category_cc')
    )
    op.create_table('payee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_payee_name')
    )
    op.create_table('recurringcandidateexclusion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('signature_hash', sa.String(length=64), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'signature_hash', name='uq_recurring_candidate_exclusion')
    )
    with op.batch_alter_table('recurringcandidateexclusion', schema=None) as batch_op:
        batch_op.create_index('ix_recurring_exclusion_user_created', ['user_id', 'created_at'], unique=False)

    op.create_table('statisticspreset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('selected_category_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_statistics_preset_user_name')
    )
    with op.batch_alter_table('statisticspreset', schema=None) as batch_op:
        batch_op.create_index('ix_statistics_preset_user', ['user_id'], unique=False)

    op.create_table('statisticssetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('excluded_category_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tag_name')
    )
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Enum('MONTH', 'WEEK', 'CUSTOM', name='budgetperiod'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('rollover', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'period_start', 'period_end', name='uq_budget_span')
    )
    op.create_table('recurringrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', 'SETTLEMENT', name='txntype'), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='recurringfrequency'), nullable=False),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('from_account_id', sa.Integer(), nullable=True),
    sa.Column('to_account_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('payee_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_generated_at', sa.Date(), nullable=True),
    sa.Column('is_variable_amount', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(type = 'TRANSFER' AND from_account_id IS NOT NULL AND to_account_id IS NOT NULL AND category_id IS NULL) OR (type = 'EXPENSE' AND from_account_id IS NOT NULL) OR (type = 'INCOME' AND to_account_id IS NOT NULL)", name='ck_recurring_type_rules'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['from_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['payee_id'], ['payee.id'], ),
    sa.ForeignKeyConstraint(['to_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_recurring_name')
    )
    op.create_table('transactiontag',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('transaction_id', 'tag_id')
    )
    op.create_table('recurringoccurrencedraft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['recurringrule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'occurred_at', name='uq_recurring_draft_rule_date')
    )
    with op.batch_alter_table('recurringoccurrencedraft', schema=None) as batch_op:
        batch_op.create_index('ix_recurring_draft_user_date', ['user_id', 'occurred_at'], unique=False)

    op.create_table('recurringoccurrenceskip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['recurringrule.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'occurred_at', name='uq_recurring_skip_rule_date')
    )
    with op.batch_alter_table('recurringoccurrenceskip', schema=None) as batch_op:
        batch_op.create_index('ix_recurring_skip_user_date', ['user_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurringoccurrenceskip', schema=None) as batch_op:
        batch_op.drop_index('ix_recurring_skip_user_date')

    op.drop_table('recurringoccurrenceskip')
    with op.batch_alter_table('recurringoccurrencedraft', schema=None) as batch_op:
        batch_op.drop_index('ix_recurring_draft_user_date')

    op.drop_table('recurringoccurrencedraft')
    op.drop_table('transactiontag')
    op.drop_table('recurringrule')
    op.drop_table('budget')
    op.drop_table('userprofile')
    op.drop_table('tag')
    op.drop_table('statisticssetting')
    with op.batch_alter_table('statisticspreset', schema=None) as batch_op:
        batch_op.drop_index('ix_statistics_preset_user')

    op.drop_table('statisticspreset')
    with op.batch_alter_table('recurringcandidateexclusion', schema=None) as batch_op:
        batch_op.drop_index('ix_recurring_exclusion_user_created')

    op.drop_table('recurringcandidateexclusion')
    op.drop_table('payee')
    op.drop_table('category')
    with op.batch_alter_table('calendarevent', schema=None) as batch_op:
        batch_op.drop_index('ix_calendar_event_user_date')

    op.drop_table('calendarevent')
    op.drop_table('account')
    op.drop_table('user')
    op.drop_table('transfergroup')
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_user_date')
        batch_op.drop_index('ix_txn_card_account_id')

    op.drop_table('transaction')
    op.drop_table('exchangerate')
    op.drop_table('currency')
    op.drop_table('creditcardstatement')
    op.drop_table('categorygroup')
    # ### end Alembic commands ###
